/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.tocraft.gradle.preprocess;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'org.example.greeting' plugin.
 */
class PreProcessorTest {
    private static final Map<String, Object> vars = new HashMap<>() {
        {
            put("zero", "0");
            put("one", "1");
            put("two", "2");
            put("test", "hello");
        }
    };

    private static final PreProcessor preProcessor = new PreProcessor(vars);

    @Test
    void testEvalExpression() {
        // existence of vars
        assertFalse(preProcessor.evalExpression("zero"));
        assertTrue(preProcessor.evalExpression("one"));
        assertTrue(preProcessor.evalExpression("test"));
        assertFalse(preProcessor.evalExpression("invalid"));
        // a == b
        assertFalse(preProcessor.evalExpression("one == 0"));
        assertTrue(preProcessor.evalExpression("one == 1"));
        assertFalse(preProcessor.evalExpression("1 == zero"));
        assertTrue(preProcessor.evalExpression("1 == one"));
        // a != b
        assertFalse(preProcessor.evalExpression("zero != 0"));
        assertTrue(preProcessor.evalExpression("zero != 1"));
        assertTrue(preProcessor.evalExpression("zero != one"));
        assertFalse(preProcessor.evalExpression("one != 1"));
        // a > b
        assertTrue(preProcessor.evalExpression("one > 0"));
        assertFalse(preProcessor.evalExpression("one > 1"));
        assertFalse(preProcessor.evalExpression("one > 2"));
        assertTrue(preProcessor.evalExpression("1 > zero"));
        assertFalse(preProcessor.evalExpression("1 > one"));
        assertFalse(preProcessor.evalExpression("1 > two"));
        // a >= b
        assertTrue(preProcessor.evalExpression("one >= 0"));
        assertTrue(preProcessor.evalExpression("one >= 1"));
        assertFalse(preProcessor.evalExpression("one >= 2"));
        assertTrue(preProcessor.evalExpression("1 >= zero"));
        assertTrue(preProcessor.evalExpression("1 >= one"));
        assertFalse(preProcessor.evalExpression("1 >= two"));
        // a < b
        assertFalse(preProcessor.evalExpression("one < 0"));
        assertFalse(preProcessor.evalExpression("one < 1"));
        assertTrue(preProcessor.evalExpression("one < 2"));
        assertFalse(preProcessor.evalExpression("1 < zero"));
        assertFalse(preProcessor.evalExpression("1 < one"));
        assertTrue(preProcessor.evalExpression("1 < two"));
        // a <= b
        assertFalse(preProcessor.evalExpression("one <= 0"));
        assertTrue(preProcessor.evalExpression("one <= 1"));
        assertTrue(preProcessor.evalExpression("one <= 2"));
        assertFalse(preProcessor.evalExpression("1 <= zero"));
        assertTrue(preProcessor.evalExpression("1 <= one"));
        assertTrue(preProcessor.evalExpression("1 <= two"));
        // a && b
        assertTrue(preProcessor.evalExpression("one && one"));
        assertFalse(preProcessor.evalExpression("one && zero"));
        assertFalse(preProcessor.evalExpression("zero && one"));
        assertFalse(preProcessor.evalExpression("zero && zero"));
        // a || b
        assertTrue(preProcessor.evalExpression("one || one"));
        assertTrue(preProcessor.evalExpression("one || zero"));
        assertTrue(preProcessor.evalExpression("zero || one"));
        assertFalse(preProcessor.evalExpression("zero || zero"));
        // ||and && nested
        assertTrue(preProcessor.evalExpression("one && one || one"));
        assertTrue(preProcessor.evalExpression("one && zero || one"));
        assertFalse(preProcessor.evalExpression("one && zero || one && zero"));
        assertTrue(preProcessor.evalExpression("one || zero && one || zero"));
        assertFalse(preProcessor.evalExpression("zero || zero && one || zero"));
    }

    @Test
    void testConvertSource() {
        // unexpected endif
        assertThrows(ParseException.class, () -> preProcessor.convertSource(new ArrayList<>() {
            {
                add("//#endif");
            }
        }));
        // unexpected else
        assertThrows(ParseException.class, () -> preProcessor.convertSource(new ArrayList<>() {
            {
                add("//#else");
            }
        }));
        // unexpected elseif
        assertThrows(ParseException.class, () -> preProcessor.convertSource(new ArrayList<>() {
            {
                add("//#elseif");
            }
        }));
        // elseif after else
        assertThrows(ParseException.class, () -> preProcessor.convertSource("""
                //#if one
                //#else
                //#elseif one
                //#endif
                """.lines().toList()));
        // missing endif
        assertThrows(ParseException.class, () -> preProcessor.convertSource("""
                //#if one
                """.lines().toList()));
        assertThrows(ParseException.class, () -> preProcessor.convertSource("""
                //#if one
                //#if one
                //#if one
                //#endif
                """.lines().toList()));
        // missing space
        assertThrows(ParseException.class, () -> preProcessor.convertSource("""
                //#ifone
                //#endif
                """.lines().toList()));
        assertThrows(ParseException.class, () -> preProcessor.convertSource("""
                //#if zero
                //#elseiftwo
                //#endif
                """.lines().toList()));
        // empty if condition
        assertThrows(ParseException.class, () -> preProcessor.convertSource("""
                //#if
                //#endif
                """.lines().toList()));

        // test with code
        // if one ... endif
        assertEquals("""
                //#if one
                code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if one
                code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if one
                code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if one
                //$$ code
                //#endif
                """.lines().toList()));
        // if zero ... endif
        assertEquals("""
                //#if zero
                //$$ code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if zero
                //$$ code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if zero
                //$$ code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if zero
                code
                //#endif
                """.lines().toList()));
        // if one ... else ... endif
        assertEquals("""
                //#if one
                code
                //#else
                //$$ code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if one
                code
                //#else
                //$$ code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if one
                code
                //#else
                //$$ code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if one
                //$$ code
                //#else
                code
                //#endif
                """.lines().toList()));
        // if zero ... else ... endif
        assertEquals("""
                //#if zero
                //$$ code
                //#else
                code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if zero
                code
                //#else
                //$$ code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if zero
                //$$ code
                //#else
                code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if zero
                //$$ code
                //#else
                code
                //#endif
                """.lines().toList()));
        // if one ... elseif zero ... endif
        assertEquals("""
                //#if one
                code
                //#elseif zero
                //$$ code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if one
                code
                //#elseif zero
                //$$ code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if one
                code
                //#elseif zero
                //$$ code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if one
                //$$ code
                //#elseif zero
                code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if one
                code
                //#elseif zero
                //$$ code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if one
                code
                //#elseif zero
                code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if one
                code
                //#elseif zero
                //$$ code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if one
                //$$ code
                //#elseif zero
                //$$ code
                //#endif
                """.lines().toList()));
        // if zero ... elseif one ... endif
        assertEquals("""
                //#if zero
                //$$ code
                //#elseif one
                code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if zero
                //$$ code
                //#elseif one
                code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if zero
                //$$ code
                //#elseif one
                code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if zero
                code
                //#elseif one
                //$$ code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if zero
                //$$ code
                //#elseif one
                code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if zero
                //$$ code
                //#elseif one
                //$$ code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if zero
                //$$ code
                //#elseif one
                code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if zero
                code
                //#elseif one
                code
                //#endif
                """.lines().toList()));
        // if one ... elseif one ... endif
        assertEquals("""
                //#if one
                code
                //#elseif one
                //$$ code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if one
                code
                //#elseif one
                //$$ code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if one
                code
                //#elseif one
                //$$ code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if one
                //$$ code
                //#elseif one
                code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if one
                code
                //#elseif one
                //$$ code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if one
                //$$ code
                //#elseif one
                //$$ code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if one
                code
                //#elseif one
                //$$ code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if one
                code
                //#elseif one
                code
                //#endif
                """.lines().toList()));
        // if ... elseif ... else ... endif
        assertEquals("""
                //#if zero
                //$$ code
                //#elseif one
                code
                //#else
                //$$ code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if zero
                //$$ code
                //#elseif one
                //$$ code
                //#else
                //$$ code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if one
                code
                //#elseif one
                //$$  code
                //#else
                //$$ code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if one
                //$$ code
                //#elseif one
                //$$  code
                //#else
                //$$ code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if zero
                //$$ code
                //#elseif zero
                //$$ code
                //#else
                code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if zero
                //$$ code
                //#elseif zero
                //$$ code
                //#else
                //$$ code
                //#endif
                """.lines().toList()));
        // multiple elseif
        assertEquals("""
                //#if zero
                //$$ code
                //#elseif zero
                //$$ code
                //#elseif zero
                //$$ code
                //#elseif zero
                //$$ code
                //#elseif zero
                //$$ code
                //#else
                code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if zero
                //$$ code
                //#elseif zero
                //$$ code
                //#elseif zero
                //$$ code
                //#elseif zero
                code
                //#elseif zero
                //$$ code
                //#else
                //$$ code
                //#endif
                """.lines().toList()));
        // nested if
        assertEquals("""
                //#if zero
                       //#if zero
                       //$$ code
                       //#else
                       //$$ code
                       //#endif
                //#else
                       //#if zero
                       //$$ code
                       //#else
                       code
                       //#endif
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if zero
                       //#if zero
                       //$$ code
                       //#else
                       //$$ code
                       //#endif
                //#else
                       //#if zero
                       //$$ code
                       //#else
                       //$$ code
                       //#endif
                //#endif
                """.lines().toList()));
        // nested elseif
        assertEquals("""
                //#if zero
                       //#if zero
                       //$$ code
                       //#else
                       //$$ code
                       //#endif
                //#elseif one
                code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if zero
                       //#if zero
                       //$$ code
                       //#else
                       //$$ code
                       //#endif
                //#elseif one
                //$$ code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if zero
                //$$ code
                //#elseif one
                       //#if zero
                       //$$ code
                       //#else
                       code
                       //#endif
                //#else
                //$$ code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if zero
                code
                //#elseif one
                       //#if zero
                       code
                       //#else
                       code
                       //#endif
                //#else
                code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if zero
                //$$ code
                //#elseif zero
                       //#if zero
                       //$$ code
                       //#else
                       //$$ code
                       //#endif
                //#elseif zero
                //$$ code
                //#else
                code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if zero
                //$$ code
                //#elseif zero
                       //#if zero
                       //$$ code
                       //#else
                       //$$ code
                       //#endif
                //#elseif zero
                //$$ code
                //#else
                //$$ code
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if one
                //#elseif one
                       //#if one
                       //$$ code
                       //#else
                       //#endif
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if one
                //#elseif one
                       //#if one
                       code
                       //#else
                       //#endif
                //#endif
                """.lines().toList()));
        assertEquals("""
                //#if one
                //#elseif one
                       //#if one
                       //#endif
                //$$        code
                //#endif
                """.lines().toList(), preProcessor.convertSource("""
                //#if one
                //#elseif one
                       //#if one
                       //#endif
                       code
                //#endif
                """.lines().toList()));
    }
}
