name: Publish

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 1.8
      - name: Upload to Maven
        run: ./gradlew check publish
        env:
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}